name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_SECRET }}"
          github_token: "${{ secrets.GIT_PAT }}"
          ado_organization: "AzureDevopsWorld"
          ado_project: "Boards"
          ado_area_path: "Boards"
          ado_iteration_path: "Boards\\Iteration 1"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
